### ISSUE TITLE
Error when using neural network rules

### ISSUE THREAD

**Issue by cattaneod** [valentjn/vscode-ltex#12]
When getting suggestions based on neural network rules, it gives me the following error:

`[Error - 12:46:12] Request textDocument/codeAction failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniApply(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.complete(Unknown Source)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:212)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException`

However, the suggestions still work normally, just the console give that error.

**Comment by valentjn** [comment]
@catta202000 The stack trace only tells us there is a `NullPointerException` somewhere, so I need to reproduce this. I've never used neural network rules. Could you add steps to reproduce this (what do I have to install, to which directory did you set `ltex.additionalRules.neuralNetworkModel`, etc.) or point me to some instructions?

**Comment by cattaneod** [comment]
Ok, my settings are:

`
"ltex.additionalRules.languageModel": "C:\\LanguageTool\\ngrams",
"ltex.additionalRules.word2VecModel": "C:\\LanguageTool\\word2vec",
"ltex.additionalRules.motherTongue": "it",
"ltex.language": "en-GB",
`

Both n-grams and word2vec are the models downloaded from the languagetool website.

A sentence that gives the error:
"And the taken."

**Comment by valentjn** [comment]
Fix released in 4.7.3.
