### ISSUE TITLE
Apple Silicon / M1 support

### ISSUE THREAD

**Issue by hippwn** [valentjn/vscode-ltex#224]
**Is your feature request related to a problem? Please describe.**
The extension does not run on Apple's new chip, even though VSCode does, as well as does Java.

**Describe the solution you'd like**
M1 support out of the box.

**Describe alternatives you've considered**
I tried to follow the offline installation guide by installing AdoptOpenJDK's latest build for ARM/M1 but unfortunatly, the extension seems not to detect Java even if the `$JAVA_HOME` is correctly set.

Thanks!

**Comment by valentjn** [comment]
This should be a bug report, as the platform is supported by LT<sub>E</sub>X if VS Code and Java are supported.

Have you tried setting [`ltex.java.path`](https://valentjn.github.io/vscode-ltex/docs/settings.html#ltexjavapath) to the same value as `JAVA_HOME`? Can you post the `LTeX Language Client/Server` logs as explained [here](https://valentjn.github.io/vscode-ltex/docs/contributing-code-issues.html#how-to-report-bugs)?

**Comment by hippwn** [comment]
Sorry for the wrong categorizing. 

Also sorry for the misunderstanding, what I meant is that I've set `ltex.java.path` (as `/Library/Java/JavaVirtualMachines/zulu-15.jdk/Contents/Home`, zulu is providing the JDK M1 support). 

Here's the output:
```
2021-01-16T18:03:05.219Z Info: Setting LTeX UI language to 'fr'.
2021-01-16T18:03:05.219Z Info: Loading i18n messages...
2021-01-16T18:03:05.220Z Info: Loading default i18n messages...
2021-01-16T18:03:05.221Z Info: 
2021-01-16T18:03:05.221Z Info: ltex.ltex-ls.path not set.
2021-01-16T18:03:05.221Z Info: Searching for ltex-ls in '/Users/<redacted>/.vscode-insiders/extensions/valentjn.vscode-ltex-8.2.1/lib'...
2021-01-16T18:03:05.221Z Info: ltex-ls found in '/Users/<redacted>/.vscode-insiders/extensions/valentjn.vscode-ltex-8.2.1/lib/ltex-ls-9.0.1'.
2021-01-16T18:03:17.918Z Info: Using Java from '/Library/Java/JavaVirtualMachines/zulu-15.jdk/Contents/Home'.
2021-01-16T18:03:17.918Z Info: Testing ltex-ls...
2021-01-16T18:03:17.918Z Info:   Command: "/Users/<redacted>/.vscode-insiders/extensions/valentjn.vscode-ltex-8.2.1/lib/ltex-ls-9.0.1/bin/ltex-ls"
2021-01-16T18:03:17.918Z Info:   Arguments: ["--version"]
2021-01-16T18:03:17.918Z Info:   env['JAVA_HOME']: "/Library/Java/JavaVirtualMachines/zulu-15.jdk/Contents/Home"
2021-01-16T18:03:17.918Z Info:   env['JAVA_OPTS']: "-Xms64m -Xmx512m"
2021-01-16T18:03:17.968Z Error: Test failed.
2021-01-16T18:03:17.968Z Error: Error details:
2021-01-16T18:03:17.968Z Error: Error: spawnSync /Users/<redacted>/.vscode-insiders/extensions/valentjn.vscode-ltex-8.2.1/lib/ltex-ls-9.0.1/bin/ltex-ls EACCES
2021-01-16T18:03:17.968Z Error: 	at Object.spawnSync (internal/child_process.js:1041:20)
2021-01-16T18:03:17.968Z Error: 	at Object.spawnSync (child_process.js:625:24)
2021-01-16T18:03:17.968Z Error: 	at _.<anonymous> (/Users/<redacted>/.vscode-insiders/extensions/valentjn.vscode-ltex-8.2.1/dist/extension.js:1:142908)
2021-01-16T18:03:17.968Z Error: 	at Generator.next (<anonymous>)
2021-01-16T18:03:17.968Z Error: 	at o (/Users/<redacted>/.vscode-insiders/extensions/valentjn.vscode-ltex-8.2.1/dist/extension.js:1:133370)
2021-01-16T18:03:17.968Z Error: 	at processTicksAndRejections (internal/process/task_queues.js:97:5)
2021-01-16T18:03:17.968Z Info: ltex-ls did not print expected version information to stdout.
2021-01-16T18:03:17.968Z Info: stdout of ltex-ls:
2021-01-16T18:03:17.968Z Info: 
2021-01-16T18:03:17.968Z Info: stderr of ltex-ls:
2021-01-16T18:03:17.968Z Info: 
2021-01-16T18:03:17.968Z Info: 
2021-01-16T18:03:17.968Z Info: ltex.java.path set to '/Library/Java/JavaVirtualMachines/zulu-15.jdk/Contents/Home'.
2021-01-16T18:03:17.968Z Info: Using ltex-ls from '/Users/<redacted>/.vscode-insiders/extensions/valentjn.vscode-ltex-8.2.1/lib/ltex-ls-9.0.1'.
2021-01-16T18:03:17.968Z Info: Using Java from '/Library/Java/JavaVirtualMachines/zulu-15.jdk/Contents/Home'.
2021-01-16T18:03:17.968Z Info: Testing ltex-ls...
2021-01-16T18:03:17.968Z Info:   Command: "/Users/<redacted>/.vscode-insiders/extensions/valentjn.vscode-ltex-8.2.1/lib/ltex-ls-9.0.1/bin/ltex-ls"
2021-01-16T18:03:17.968Z Info:   Arguments: ["--version"]
2021-01-16T18:03:17.968Z Info:   env['JAVA_HOME']: "/Library/Java/JavaVirtualMachines/zulu-15.jdk/Contents/Home"
2021-01-16T18:03:17.968Z Info:   env['JAVA_OPTS']: "-Xms64m -Xmx512m"
2021-01-16T18:03:18.017Z Error: Test failed.
2021-01-16T18:03:18.017Z Error: Error details:
2021-01-16T18:03:18.018Z Error: Error: spawnSync /Users/<redacted>/.vscode-insiders/extensions/valentjn.vscode-ltex-8.2.1/lib/ltex-ls-9.0.1/bin/ltex-ls EACCES
2021-01-16T18:03:18.018Z Error: 	at Object.spawnSync (internal/child_process.js:1041:20)
2021-01-16T18:03:18.018Z Error: 	at Object.spawnSync (child_process.js:625:24)
2021-01-16T18:03:18.018Z Error: 	at _.<anonymous> (/Users/<redacted>/.vscode-insiders/extensions/valentjn.vscode-ltex-8.2.1/dist/extension.js:1:142908)
2021-01-16T18:03:18.018Z Error: 	at Generator.next (<anonymous>)
2021-01-16T18:03:18.018Z Error: 	at o (/Users/<redacted>/.vscode-insiders/extensions/valentjn.vscode-ltex-8.2.1/dist/extension.js:1:133370)
2021-01-16T18:03:18.018Z Error: 	at processTicksAndRejections (internal/process/task_queues.js:97:5)
2021-01-16T18:03:18.018Z Info: ltex-ls did not print expected version information to stdout.
2021-01-16T18:03:18.018Z Info: stdout of ltex-ls:
2021-01-16T18:03:18.018Z Info: 
2021-01-16T18:03:18.018Z Info: stderr of ltex-ls:
2021-01-16T18:03:18.018Z Info: 
2021-01-16T18:03:18.018Z Error: The download/extraction/run of Java failed!
2021-01-16T18:03:18.018Z Info: You might want to try offline installation, see https://valentjn.github.io/vscode-ltex/docs/installation-and-usage.html#offline-installation.

```

**Comment by valentjn** [comment]
`EACCES` sounds like maybe it's a permission issue.

Can you try it in a console (that's what LT<sub>E</sub>X tries to run)?

```bash
export JAVA_HOME="/Library/Java/JavaVirtualMachines/zulu-15.jdk/Contents/Home"
export JAVA_OPTS="-Xms64m -Xmx512m"
/Users/<redacted>/.vscode-insiders/extensions/valentjn.vscode-ltex-8.2.1/lib/ltex-ls-9.0.1/bin/ltex-ls --version
```

Is the `x` bit set on `ltex-ls` (set via `chmod +x /Users/<redacted>/.vscode-insiders/extensions/valentjn.vscode-ltex-8.2.1/lib/ltex-ls-9.0.1/bin/ltex-ls` and run the commands above again)?

**Comment by hippwn** [comment]
> `EACCES` sounds like maybe it's a permission issue.

It was! I haven't thought of that, thanks! I don't know why though, I would have thought that permissions would have been set at installation... Well thanks anyway!

**Comment by lewoking** [comment]
021-01-19T09:35:21.963Z Info: 
2021-01-19T09:35:21.963Z Info: ltex.java.path set to '/opt/homebrew/Cellar/openjdk/15.0.1/libexec/openjdk.jdk/Contents/Home'.
2021-01-19T09:35:21.963Z Info: Using ltex-ls from '/Users/liujg/.vscode-insiders/extensions/valentjn.vscode-ltex-8.2.1/lib/ltex-ls-9.0.1'.
2021-01-19T09:35:21.963Z Info: Using Java from '/opt/homebrew/Cellar/openjdk/15.0.1/libexec/openjdk.jdk/Contents/Home'.
2021-01-19T09:35:21.964Z Info: Testing ltex-ls...
2021-01-19T09:35:21.964Z Info:   Command: "/Users/liujg/.vscode-insiders/extensions/valentjn.vscode-ltex-8.2.1/lib/ltex-ls-9.0.1/bin/ltex-ls"
2021-01-19T09:35:21.964Z Info:   Arguments: ["--version"]
2021-01-19T09:35:21.964Z Info:   env['JAVA_HOME']: "/opt/homebrew/Cellar/openjdk/15.0.1/libexec/openjdk.jdk/Contents/Home"
2021-01-19T09:35:21.964Z Info:   env['JAVA_OPTS']: "-Xms64m -Xmx512m"
2021-01-19T09:35:22.200Z Error: Test failed.
2021-01-19T09:35:22.200Z Info: ltex-ls did not print expected version information to stdout.
2021-01-19T09:35:22.200Z Info: stdout of ltex-ls:
2021-01-19T09:35:22.200Z Info: {
2021-01-19T09:35:22.200Z Info:   "ltex-ls": "9.0.1",
2021-01-19T09:35:22.200Z Info:   "java": "16"
2021-01-19T09:35:22.200Z Info: }
2021-01-19T09:35:22.200Z Info: 
2021-01-19T09:35:22.200Z Info: stderr of ltex-ls:
2021-01-19T09:35:22.200Z Info: 
2021-01-19T09:35:22.204Z Info: 
2021-01-19T09:35:22.204Z Info: ltex.java.path set to '/opt/homebrew/Cellar/openjdk/15.0.1/libexec/openjdk.jdk/Contents/Home'.
2021-01-19T09:35:22.204Z Info: Using ltex-ls from '/Users/liujg/.vscode-insiders/extensions/valentjn.vscode-ltex-8.2.1/lib/ltex-ls-9.0.1'.
2021-01-19T09:35:22.204Z Info: Using Java from '/opt/homebrew/Cellar/openjdk/15.0.1/libexec/openjdk.jdk/Contents/Home'.
2021-01-19T09:35:22.204Z Info: Testing ltex-ls...
2021-01-19T09:35:22.204Z Info:   Command: "/Users/liujg/.vscode-insiders/extensions/valentjn.vscode-ltex-8.2.1/lib/ltex-ls-9.0.1/bin/ltex-ls"
2021-01-19T09:35:22.204Z Info:   Arguments: ["--version"]
2021-01-19T09:35:22.204Z Info:   env['JAVA_HOME']: "/opt/homebrew/Cellar/openjdk/15.0.1/libexec/openjdk.jdk/Contents/Home"
2021-01-19T09:35:22.204Z Info:   env['JAVA_OPTS']: "-Xms64m -Xmx512m"
2021-01-19T09:35:22.432Z Error: Test failed.
2021-01-19T09:35:22.432Z Info: ltex-ls did not print expected version information to stdout.
2021-01-19T09:35:22.432Z Info: stdout of ltex-ls:
2021-01-19T09:35:22.432Z Info: {
2021-01-19T09:35:22.432Z Info:   "ltex-ls": "9.0.1",
2021-01-19T09:35:22.432Z Info:   "java": "16"
2021-01-19T09:35:22.432Z Info: }
2021-01-19T09:35:22.432Z Info: 
2021-01-19T09:35:22.432Z Info: stderr of ltex-ls:
2021-01-19T09:35:22.432Z Info: 
2021-01-19T09:35:22.432Z Info: 
2021-01-19T09:35:22.432Z Info: ltex.java.path set to '/opt/homebrew/Cellar/openjdk/15.0.1/libexec/openjdk.jdk/Contents/Home'.
2021-01-19T09:35:22.432Z Info: Using ltex-ls from '/Users/liujg/.vscode-insiders/extensions/valentjn.vscode-ltex-8.2.1/lib/ltex-ls-9.0.1'.
2021-01-19T09:35:22.432Z Info: Using Java from '/opt/homebrew/Cellar/openjdk/15.0.1/libexec/openjdk.jdk/Contents/Home'.
2021-01-19T09:35:22.432Z Info: Testing ltex-ls...
2021-01-19T09:35:22.432Z Info:   Command: "/Users/liujg/.vscode-insiders/extensions/valentjn.vscode-ltex-8.2.1/lib/ltex-ls-9.0.1/bin/ltex-ls"
2021-01-19T09:35:22.432Z Info:   Arguments: ["--version"]
2021-01-19T09:35:22.432Z Info:   env['JAVA_HOME']: "/opt/homebrew/Cellar/openjdk/15.0.1/libexec/openjdk.jdk/Contents/Home"
2021-01-19T09:35:22.432Z Info:   env['JAVA_OPTS']: "-Xms64m -Xmx512m"
2021-01-19T09:35:22.651Z Error: Test failed.
2021-01-19T09:35:22.651Z Info: ltex-ls did not print expected version information to stdout.
2021-01-19T09:35:22.651Z Info: stdout of ltex-ls:
2021-01-19T09:35:22.651Z Info: {
2021-01-19T09:35:22.651Z Info:   "ltex-ls": "9.0.1",
2021-01-19T09:35:22.651Z Info:   "java": "16"
2021-01-19T09:35:22.651Z Info: }
2021-01-19T09:35:22.651Z Info: 
2021-01-19T09:35:22.651Z Info: stderr of ltex-ls:
2021-01-19T09:35:22.651Z Info: 
2021-01-19T09:35:22.651Z Error: The download/extraction/run of Java failed!
2021-01-19T09:35:22.651Z Info: You might want to try offline installation, see https://valentjn.github.io/vscode-ltex/docs/installation-and-usage.html#offline-installation.

**Comment by valentjn** [comment]
The permissions are set in the ltex-ls archive that vscode-ltex downloads, e.g., https://github.com/valentjn/ltex-ls/releases/download/9.0.1/ltex-ls-9.0.1.tar.gz. vscode-ltex then uses the [tar Node.js module](https://www.npmjs.com/package/tar) to extract that. If the `x` bit is missing after extraction and this can be reproduced (vscode-ltex will redownload ltex-ls if you remove the extracted directory `.../lib/ltex-ls-9.0.1`, plus after every update), then there's probably a bug in the tar module or a dependency of it.

@lewoking Your issue is unrelated to this one, it should be fixed now. Next time please open a new issue instead of just pasting a log file into an existing issue.
