### ISSUE TITLE
RuntimeException: fromPos must be less than toPos 

### ISSUE THREAD

**Issue by alexandres** [valentjn/vscode-ltex#389]
**Describe the bug**

Checking fails silently. After successfully reporting a couple of problems, checking stops and LTeX Language Server logs show:

```
SEVERE: LanguageTool failed. The following exception occurred:
java.lang.RuntimeException: java.lang.RuntimeException: fromPos (163292) must be less than toPos (163292) for match: <sentcontent>SENTENCE_WHITESPACE:64378-64386:Add a space between sentences.</sentcontent>
	at org.languagetool.JLanguageTool.performCheck(JLanguageTool.java:1233)
	at org.languagetool.JLanguageTool.checkInternal(JLanguageTool.java:973)
	at org.languagetool.JLanguageTool.check(JLanguageTool.java:903)
	at org.languagetool.JLanguageTool.check(JLanguageTool.java:885)
	at org.languagetool.JLanguageTool.check(JLanguageTool.java:872)
	at org.bsplines.ltexls.languagetool.LanguageToolJavaInterface.check(LanguageToolJavaInterface.kt:110)
	at org.bsplines.ltexls.server.DocumentChecker.checkAnnotatedTextFragment(DocumentChecker.kt:112)
	at org.bsplines.ltexls.server.DocumentChecker.checkAnnotatedTextFragments(DocumentChecker.kt:77)
	at org.bsplines.ltexls.server.DocumentChecker.check(DocumentChecker.kt:225)
	at org.bsplines.ltexls.server.LtexTextDocumentItem.check(LtexTextDocumentItem.kt:404)
	at org.bsplines.ltexls.server.LtexTextDocumentItem.checkAndGetDiagnostics(LtexTextDocumentItem.kt:289)
	at org.bsplines.ltexls.server.LtexTextDocumentItem.checkAndPublishDiagnostics(LtexTextDocumentItem.kt:266)
	at org.bsplines.ltexls.server.LtexTextDocumentItem.checkAndPublishDiagnosticsWithoutCache(LtexTextDocumentItem.kt:261)
	at org.bsplines.ltexls.server.LtexTextDocumentItem.checkAndPublishDiagnosticsWithoutCache$default(LtexTextDocumentItem.kt:260)
	at org.bsplines.ltexls.server.LtexTextDocumentService.didOpen$lambda-0(LtexTextDocumentService.kt:136)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: fromPos (163292) must be less than toPos (163292) for match: <sentcontent>SENTENCE_WHITESPACE:64378-64386:Add a space between sentences.</sentcontent>
	at org.languagetool.rules.RuleMatch.setOffsetPosition(RuleMatch.java:326)
	at org.languagetool.JLanguageTool$TextCheckCallable.getTextLevelRuleMatches(JLanguageTool.java:1810)
	at org.languagetool.JLanguageTool$TextCheckCallable.call(JLanguageTool.java:1767)
	at org.languagetool.JLanguageTool$TextCheckCallable.call(JLanguageTool.java:1739)
	at org.languagetool.JLanguageTool.performCheck(JLanguageTool.java:1229)
	... 20 more
```

**Steps to reproduce**

I'd like to create a sample document that reproduces the issue, but I need to know where the error is occurring. Can you deduce that from the error message above?

**Expected behavior**

Checks continue the end of the document.

**Sample document**

> I'd like to create a sample document that reproduces the issue, but I need to know where the error is occurring. Can you deduce that from the error message above?

**Version information**
List here the version information of the relevant software.

- Operating system: macOS 10.15.7
- VS Code: 1.58.1
- vscode-ltex: 11.0.0
- ltex-ls: bundled
- Java: bundled

**Additional context/information**
 
None.

Thank you for the the effort on this much needed tool. 🤗

**Comment by valentjn** [comment]
Thanks for the report. Looks like a bug in LanguageTool to me.

No, I don't know where in the document the error occurs (163292 is only the position in the plaintext after stripping markup).

Can you perform a bisection? Delete the first half of the document, and try to reproduce the error. If it still occurs, use this half in the next iteration. Otherwise, undo and use the first half. Rinse and repeat, until your example is minimal.

**Comment by alexandres** [comment]
Does LTeX depend on Latex *structure*? Can I safely dangle open environs when performing the bisection?

**Comment by valentjn** [comment]
Of course, with ”half“ I didn't mean to cut exactly after n/2 bytes. Do the cuts around commands and environments. If your current iteration is wrapped in one large environment, remove `\begin{...}` and `\end{...}` first and see if the bug is still there.

**Comment by alexandres** [comment]
Found it! 

```tex
$S_{\textnormal{cat}} = \{ \textnormal{$\langle$ ca, at$\rangle$, cat} \}$
```

Removing the nested equations (the $...$ within the outher $...$) fixes the problem. It's valid TeX, but I guess there's some parsing rule in LTeX that doesn't expect it.

**Comment by valentjn** [comment]
Can't reproduce this. Doesn't matter if with trailing newline or without. Are you sure this is exactly the document?

**Comment by douira** [comment]
This piece of LaTeX code `$a$$a$. $a$. $a$.` (as the only text in a .tex file) causes this error for me:

```
Aug 13, 2022 7:21:23 PM org.bsplines.ltexls.server.DocumentChecker logTextToBeChecked
FINE: Checking the following text in language 'de-DE' via LanguageTool: "Dummy0.Dummy1."
Aug 13, 2022 7:21:23 PM org.bsplines.ltexls.server.DocumentChecker checkAnnotatedTextFragment
SEVERE: LanguageTool failed. The following exception occurred:
java.lang.RuntimeException: java.lang.RuntimeException: fromPos (13) must be less than toPos (13) for match: <sentcontent>DE_SENTENCE_WHITESPACE:7-13:Fügen Sie zwischen Sätzen ein Leerzeichen ein</sentcontent>
	at org.languagetool.JLanguageTool.performCheck(JLanguageTool.java:1233)
	at org.languagetool.JLanguageTool.checkInternal(JLanguageTool.java:973)
	at org.languagetool.JLanguageTool.check(JLanguageTool.java:903)
	at org.languagetool.JLanguageTool.check(JLanguageTool.java:885)
	at org.languagetool.JLanguageTool.check(JLanguageTool.java:872)
	at org.bsplines.ltexls.languagetool.LanguageToolJavaInterface.check(LanguageToolJavaInterface.kt:110)
	at org.bsplines.ltexls.server.DocumentChecker.checkAnnotatedTextFragment(DocumentChecker.kt:112)
	at org.bsplines.ltexls.server.DocumentChecker.checkAnnotatedTextFragments(DocumentChecker.kt:77)
	at org.bsplines.ltexls.server.DocumentChecker.check(DocumentChecker.kt:225)
	at org.bsplines.ltexls.server.LtexTextDocumentItem.check(LtexTextDocumentItem.kt:404)
	at org.bsplines.ltexls.server.LtexTextDocumentItem.checkAndGetDiagnostics(LtexTextDocumentItem.kt:289)
	at org.bsplines.ltexls.server.LtexTextDocumentItem.checkAndPublishDiagnostics(LtexTextDocumentItem.kt:266)
	at org.bsplines.ltexls.server.LtexTextDocumentItem.checkAndPublishDiagnosticsWithoutCache(LtexTextDocumentItem.kt:261)
	at org.bsplines.ltexls.server.LtexTextDocumentItem.checkAndPublishDiagnosticsWithoutCache$default(LtexTextDocumentItem.kt:260)
	at org.bsplines.ltexls.server.LtexTextDocumentService.didSave$lambda-1(LtexTextDocumentService.kt:178)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: fromPos (13) must be less than toPos (13) for match: <sentcontent>DE_SENTENCE_WHITESPACE:7-13:Fügen Sie zwischen Sätzen ein Leerzeichen ein</sentcontent>
	at org.languagetool.rules.RuleMatch.setOffsetPosition(RuleMatch.java:326)
	at org.languagetool.JLanguageTool$TextCheckCallable.getTextLevelRuleMatches(JLanguageTool.java:1810)
	at org.languagetool.JLanguageTool$TextCheckCallable.call(JLanguageTool.java:1767)
	at org.languagetool.JLanguageTool$TextCheckCallable.call(JLanguageTool.java:1739)
	at org.languagetool.JLanguageTool.performCheck(JLanguageTool.java:1229)
	... 20 more
```
I believe this is the same error.
