### ISSUE TITLE
Coc_ltex fails with Header must provide a Content-Length

### ISSUE THREAD

**Issue by felix-ulonska** [valentjn/vscode-ltex#462]
**Describe the bug**
When installing `coc-ltex` and opening a Markdown Document, the document is not being checked. At the same time following error is reported via `CocOpenLog` The following error only exists on documents which should be checked by ltex so I assume it is related
```
2021-11-15T21:10:35.387 ERROR (pid:784917) [server] - uncaughtException Error: Header must provide a Content-Length property.
    at ZS.onData (/home/jabbi/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:35:14451)
    at Socket.<anonymous> (/home/jabbi/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:35:14181)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Steps to reproduce**

1. Install nvim
2. Run `:CocInstall coc-ltex`
3. Open a document which starts the extension.

**Expected behavior**
The document should be checked.

**LTeX configuration**

<details>

```
	"ltex.ltex-ls.logLevel": "finest",
	"ltex.trace.server": "verbose",
```

</details>

**"LTeX Language Server" log file**

<details>

```
[Info  - 9:04:03 PM] Starting ltex-ls...
[Trace - 9:04:04 PM] Sending request 'initialize - (0)'.
Params: {
    "processId": 752256,
    "rootPath": "/home/jabbi/Uni-Repos/Betriebssysteme-Abgaben",
    "rootUri": "file:///home/jabbi/Uni-Repos/Betriebssysteme-Abgaben",
    "capabilities": {
        "workspace": {
            "applyEdit": true,
            "workspaceEdit": {
                "documentChanges": true,
                "resourceOperations": [
                    "create",
                    "rename",
                    "delete"
                ],
                "failureHandling": "textOnlyTransactional"
            },
            "didChangeConfiguration": {
                "dynamicRegistration": true
            },
            "didChangeWatchedFiles": {
                "dynamicRegistration": true
            },
            "symbol": {
                "dynamicRegistration": true,
                "symbolKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26
                    ]
                },
                "tagSupport": {
                    "valueSet": [
                        1
                    ]
                }
            },
            "codeLens": {
                "refreshSupport": true
            },
            "executeCommand": {
                "dynamicRegistration": true
            },
            "configuration": true,
            "semanticTokens": {
                "refreshSupport": true
            },
            "fileOperations": {
                "dynamicRegistration": true,
                "didCreate": true,
                "didRename": true,
                "didDelete": true,
                "willCreate": true,
                "willRename": true,
                "willDelete": true
            },
            "workspaceFolders": true
        },
        "textDocument": {
            "publishDiagnostics": {
                "relatedInformation": true,
                "versionSupport": false,
                "tagSupport": {
                    "valueSet": [
                        1,
                        2
                    ]
                }
            },
            "synchronization": {
                "dynamicRegistration": true,
                "willSave": true,
                "willSaveWaitUntil": true,
                "didSave": true
            },
            "completion": {
                "dynamicRegistration": true,
                "contextSupport": true,
                "completionItem": {
                    "snippetSupport": true,
                    "commitCharactersSupport": true,
                    "documentationFormat": [
                        "markdown",
                        "plaintext"
                    ],
                    "deprecatedSupport": true,
                    "preselectSupport": true,
                    "insertReplaceSupport": true,
                    "tagSupport": {
                        "valueSet": [
                            1
                        ]
                    },
                    "resolveSupport": {
                        "properties": [
                            "documentation",
                            "detail",
                            "additionalTextEdits"
                        ]
                    },
                    "insertTextModeSupport": {
                        "valueSet": [
                            1,
                            2
                        ]
                    }
                },
                "completionItemKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25
                    ]
                }
            },
            "hover": {
                "dynamicRegistration": true,
                "contentFormat": [
                    "markdown",
                    "plaintext"
                ]
            },
            "signatureHelp": {
                "dynamicRegistration": true,
                "contextSupport": true,
                "signatureInformation": {
                    "documentationFormat": [
                        "markdown",
                        "plaintext"
                    ],
                    "activeParameterSupport": true,
                    "parameterInformation": {
                        "labelOffsetSupport": true
                    }
                }
            },
            "definition": {
                "dynamicRegistration": true
            },
            "references": {
                "dynamicRegistration": true
            },
            "documentHighlight": {
                "dynamicRegistration": true
            },
            "documentSymbol": {
                "dynamicRegistration": true,
                "symbolKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26
                    ]
                },
                "hierarchicalDocumentSymbolSupport": true,
                "tagSupport": {
                    "valueSet": [
                        1
                    ]
                }
            },
            "codeAction": {
                "dynamicRegistration": true,
                "isPreferredSupport": true,
                "disabledSupport": true,
                "dataSupport": true,
                "honorsChangeAnnotations": false,
                "resolveSupport": {
                    "properties": [
                        "edit"
                    ]
                },
                "codeActionLiteralSupport": {
                    "codeActionKind": {
                        "valueSet": [
                            "",
                            "quickfix",
                            "refactor",
                            "refactor.extract",
                            "refactor.inline",
                            "refactor.rewrite",
                            "source",
                            "source.organizeImports"
                        ]
                    }
                }
            },
            "codeLens": {
                "dynamicRegistration": true
            },
            "formatting": {
                "dynamicRegistration": true
            },
            "rangeFormatting": {
                "dynamicRegistration": true
            },
            "onTypeFormatting": {
                "dynamicRegistration": true
            },
            "rename": {
                "dynamicRegistration": true,
                "prepareSupport": true
            },
            "documentLink": {
                "dynamicRegistration": true,
                "tooltipSupport": true
            },
            "typeDefinition": {
                "dynamicRegistration": true
            },
            "implementation": {
                "dynamicRegistration": true
            },
            "declaration": {
                "dynamicRegistration": true
            },
            "colorProvider": {
                "dynamicRegistration": true
            },
            "foldingRange": {
                "dynamicRegistration": true,
                "rangeLimit": 5000,
                "lineFoldingOnly": true
            },
            "selectionRange": {
                "dynamicRegistration": true
            },
            "callHierarchy": {
                "dynamicRegistration": true
            },
            "semanticTokens": {
                "dynamicRegistration": true,
                "tokenTypes": [
                    "namespace",
                    "type",
                    "class",
                    "enum",
                    "interface",
                    "struct",
                    "typeParameter",
                    "parameter",
                    "variable",
                    "property",
                    "enumMember",
                    "event",
                    "function",
                    "method",
                    "macro",
                    "keyword",
                    "modifier",
                    "comment",
                    "string",
                    "number",
                    "regexp",
                    "operator"
                ],
                "tokenModifiers": [
                    "declaration",
                    "definition",
                    "readonly",
                    "static",
                    "deprecated",
                    "abstract",
                    "async",
                    "modification",
                    "documentation",
                    "defaultLibrary"
                ],
                "formats": [
                    "relative"
                ],
                "requests": {
                    "range": true,
                    "full": {
                        "delta": true
                    }
                },
                "multilineTokenSupport": false,
                "overlappingTokenSupport": false
            },
            "linkedEditingRange": {
                "dynamicRegistration": true
            }
        },
        "window": {
            "showMessage": {
                "messageActionItem": {
                    "additionalPropertiesSupport": false
                }
            },
            "showDocument": {
                "support": false
            },
            "workDoneProgress": true
        },
        "general": {
            "regularExpressions": {
                "engine": "ECMAScript",
                "version": "ES2020"
            },
            "markdown": {
                "parser": "marked",
                "version": "1.1.0"
            }
        }
    },
    "initializationOptions": {
        "customCapabilities": {
            "workspaceSpecificConfiguration": true
        }
    },
    "trace": "verbose",
    "workspaceFolders": [
        {
            "uri": "file:///home/jabbi/Uni-Repos/Betriebssysteme-Abgaben",
            "name": "Betriebssysteme-Abgaben"
        }
    ],
    "locale": "en_US",
    "clientInfo": {
        "name": "coc.nvim",
        "version": "0.0.80"
    }
}


Nov 15, 2021 9:04:06 PM org.bsplines.ltexls.server.LtexLanguageServer initialize
INFO: ltex-ls 15.0.0 - initializing...
Nov 15, 2021 9:04:06 PM org.bsplines.ltexls.tools.I18n setLocale
INFO: Setting locale to ''
```

</details>

**"LTeX Language Client" log file**

<details>

```
2021-11-15T20:04:02.767Z Info: Setting LTeX UI language to 'en-US'.
2021-11-15T20:04:02.768Z Info: Loading i18n messages...
2021-11-15T20:04:02.769Z Info: Loading default i18n messages...
2021-11-15T20:04:02.771Z Info: 
2021-11-15T20:04:02.772Z Info: ltex.ltex-ls.path not set.
2021-11-15T20:04:02.772Z Info: Searching for ltex-ls in '/home/jabbi/.config/coc/extensions/node_modules/coc-ltex/lib'...
2021-11-15T20:04:02.772Z Info: ltex-ls found in '/home/jabbi/.config/coc/extensions/node_modules/coc-ltex/lib/ltex-ls-15.0.0'.
2021-11-15T20:04:02.772Z Info: 
2021-11-15T20:04:02.772Z Info: Using ltex-ls from '/home/jabbi/.config/coc/extensions/node_modules/coc-ltex/lib/ltex-ls-15.0.0'.
2021-11-15T20:04:02.772Z Info: Using Java bundled with ltex-ls as ltex.java.path is not set.
2021-11-15T20:04:03.375Z Info: Testing ltex-ls...
2021-11-15T20:04:03.375Z Info:   Command: "/home/jabbi/.config/coc/extensions/node_modules/coc-ltex/lib/ltex-ls-15.0.0/bin/ltex-ls"
2021-11-15T20:04:03.375Z Info:   Arguments: ["--version"]
2021-11-15T20:04:03.375Z Info:   env['JAVA_HOME']: undefined
2021-11-15T20:04:03.375Z Info:   env['JAVA_OPTS']: "-Xms64m -Xmx512m"
2021-11-15T20:04:03.971Z Info: Test successful!
2021-11-15T20:04:03.971Z Info: 
2021-11-15T20:04:03.978Z Info: Starting ltex-ls...
2021-11-15T20:04:03.978Z Info:   Command: "/home/jabbi/.config/coc/extensions/node_modules/coc-ltex/lib/ltex-ls-15.0.0/bin/ltex-ls"
2021-11-15T20:04:03.978Z Info:   Arguments: []
2021-11-15T20:04:03.978Z Info:   env['JAVA_HOME']: undefined
2021-11-15T20:04:03.978Z Info:   env['JAVA_OPTS']: "-Xms64m -Xmx512m"
2021-11-15T20:04:03.978Z Info: 
```

</details>

**Version information**
List here the version information of the relevant software.

- Operating system: Linux Bedrock (should be equal to: Pop 20.04 which is Ubuntu based)
- vscode-ltex: latest
- ltex-ls: 15.0 (downloaded by coc-ltex) 
- Java: 17

**Additional context/information**
Issue also exists when using manual download ltex

Plugin works on my machine fine in VsCode.

**Comment by felix-ulonska** [comment]
I just tried to use the language server manual with this in coc-settings.json
```
		"languageserver.tex": {
			"command": "/home/jabbi/opt/ltex-ls-15.0.0/bin/ltex-ls",
			"filetypes": ["tex", "latex", "markdown"],
			"trace.server": "verbose",
			"initializationOptions": {
				"usePlaceholders": true
			}
		}
```

I received the same errors

**Comment by valentjn** [comment]
Can you please post steps to reproduce this with a vanilla installation of Neovim (delete all existing configuration/coc.nvim etc.)? Please include all involved versions (especially Neovim and coc.nvim).

**Comment by felix-ulonska** [comment]
_Sadly_ the issue resolved itself after posting. I assume that my JAVA_HOME was bad, or I used the wrong node version. On that note, for it seems that coc-ltex plugin requires node 14. 

I am extremely grateful for plugin and thank you for your work!

**Comment by valentjn** [comment]
> *Sadly* the issue resolved itself after posting.

I'm sorry to hear that ;)

> On that note, for it seems that coc-ltex plugin requires node 14.

Fixed, thanks for the info.
