### ISSUE TITLE
LTeX does not locally install arm64 java on Apple M1 Macs

### ISSUE THREAD

**Issue by deividrvale** [valentjn/vscode-ltex#634]
**Describe the bug**
Even if no java is installed system-wide, ltex will manually download a portable jdk in order to run language tool.
On x86 systems, both windows and Intel Macs, this behavior works as expected.
On the new M1 macOS, however, the automatically downloaded jdk is not correct for arm64 platform.

**Steps to reproduce**
1. Open any file that triggers the grammar checker.
2. Don't set ltex.java.path
3. The downloaded java won't run in the system.
4. 
**Error Message:**

`Could not run ltex-ls with Java, please see the output panel 'LTeX Language Client' for details. You might want to try offline installation.`

**Output trace:**
```
2022-06-10T22:00:14.035Z Info: Setting LTeX UI language to 'en-gb'.
2022-06-10T22:00:14.035Z Info: Loading i18n messages...
2022-06-10T22:00:14.035Z Info: Loading default i18n messages...
2022-06-10T22:00:14.036Z Info: 
2022-06-10T22:00:14.036Z Info: ltex.ltex-ls.path not set.
2022-06-10T22:00:14.036Z Info: Searching for ltex-ls in '/Users/deividvale/.vscode/extensions/valentjn.vscode-ltex-13.1.0/lib'...
2022-06-10T22:00:14.036Z Info: ltex-ls found in '/Users/deividvale/.vscode/extensions/valentjn.vscode-ltex-13.1.0/lib/ltex-ls-15.2.0'.
2022-06-10T22:00:14.036Z Info: 
2022-06-10T22:00:14.036Z Info: Using ltex-ls from '/Users/deividvale/.vscode/extensions/valentjn.vscode-ltex-13.1.0/lib/ltex-ls-15.2.0'.
2022-06-10T22:00:14.036Z Info: Using Java bundled with ltex-ls as ltex.java.path is not set.
2022-06-10T22:00:14.038Z Info: Testing ltex-ls...
2022-06-10T22:00:14.038Z Info:   Command: "/Users/deividvale/.vscode/extensions/valentjn.vscode-ltex-13.1.0/lib/ltex-ls-15.2.0/bin/ltex-ls"
2022-06-10T22:00:14.038Z Info:   Arguments: ["--version"]
2022-06-10T22:00:14.038Z Info:   env['JAVA_HOME']: undefined
2022-06-10T22:00:14.038Z Info:   env['JAVA_OPTS']: "-Xms512m -Xmx1024m"
2022-06-10T22:00:14.045Z Error: Test failed.
2022-06-10T22:00:14.045Z Error: Error details:
2022-06-10T22:00:14.045Z Info: ltex-ls terminated with non-zero exit code 1.
2022-06-10T22:00:14.045Z Info: stdout of ltex-ls:
2022-06-10T22:00:14.045Z Info: 
2022-06-10T22:00:14.045Z Info: stderr of ltex-ls:
2022-06-10T22:00:14.045Z Info: /Users/deividvale/.vscode/extensions/valentjn.vscode-ltex-13.1.0/lib/ltex-ls-15.2.0/bin/ltex-ls: line 121: /Users/deividvale/.vscode/extensions/valentjn.vscode-ltex-13.1.0/lib/ltex-ls-15.2.0/jdk-11.0.12+7/bin/java: Bad CPU type in executable
2022-06-10T22:00:14.045Z Info: /Users/deividvale/.vscode/extensions/valentjn.vscode-ltex-13.1.0/lib/ltex-ls-15.2.0/bin/ltex-ls: line 121: /Users/deividvale/.vscode/extensions/valentjn.vscode-ltex-13.1.0/lib/ltex-ls-15.2.0/jdk-11.0.12+7/bin/java: Undefined error: 0
2022-06-10T22:00:14.045Z Info: 
2022-06-10T22:00:14.046Z Info: You might want to try offline installation, see https://valentjn.github.io/vscode-ltex/docs/installation-and-usage.html#offline-installation.
```
4. If I manually go to `/Users/deividvale/.vscode/extensions/valentjn.vscode-ltex-13.1.0/lib/ltex-ls-15.2.0/jdk-11.0.12+7/bin/java`
and run it with --version, I also get the same `Bad CPU type in executable`.

**Expected behavior**
LTeX should download the arm64 version of java when detected the architecture (perhaps this check ins't done?)

**Sample document**
If the bug occurs for a specific document (e.g. LaTeX), please paste it here. If your document is very long or confidential, please create and attach a smaller example for which the bug still occurs so that we can reproduce it.

**LTeX configuration**
Please paste all configuration settings starting with `ltex.` from your `settings.json`. You can help us by temporarily removing some irrelevant settings from your `settings.json` and see if the bug still occurs.

<details>

```
 // LTex configuration
    "ltex.language": "en-US",
    "ltex.trace.server": "verbose",
    "ltex.checkFrequency": "save",
    // "ltex.java.path": "/opt/homebrew/opt/openjdk", -- commented to report bug 
    "ltex.java.initialHeapSize": 512,
    "ltex.java.maximumHeapSize": 1024,
    "ltex.sentenceCacheSize": 20000,
    "ltex.additionalRules.motherTongue": "pt-BR",
```

</details>

**"LTeX Language Server" log file**
First, reproduce the bug. Then, go to `View` → `Output` and select `LTeX Language Server` in the drop-down list. Paste this log here:

<details>

```
REPLACE_THIS_WITH_LTEX_LANGUAGE_SERVER_LOG
```

</details>

**"LTeX Language Client" log file**
First, set the `ltex.trace.server` setting in your `settings.json` to `"verbose"`. Then, reload the VS Code window and reproduce the bug. Go to `View` → `Output` and select `LTeX Language Client` in the drop-down list. Paste this log here (note: it will contain your checked document):

<details>

```
REPLACE_THIS_WITH_LTEX_LANGUAGE_CLIENT_LOG
```

</details>

**Version information**
List here the version information of the relevant software.

- Operating system: macOS 12.4
- VS Code: 1.68.0, arm64
- vscode-ltex: v13.1.0
- ltex-ls: x.xx (only if not using ltex-ls automatically downloaded by LTeX)
- Java: x.xx (usually obtained with `java -version`, only if not using Java automatically downloaded by LTeX)

**Additional context/information**
If I set `ltex.java.path` to my own system java installation, everything works as expected.
This is the setting I'm using right now. 
I had to install openjdk on the system level to be able to use LTeX.

After `ltex.java.path` is set:
```
2022-06-10T21:48:48.768Z Info: Setting LTeX UI language to 'en-gb'.
2022-06-10T21:48:48.768Z Info: Loading i18n messages...
2022-06-10T21:48:48.768Z Info: Loading default i18n messages...
2022-06-10T21:48:48.769Z Info: 
2022-06-10T21:48:48.769Z Info: ltex.ltex-ls.path not set.
2022-06-10T21:48:48.769Z Info: Searching for ltex-ls in '/Users/deividvale/.vscode/extensions/valentjn.vscode-ltex-13.1.0/lib'...
2022-06-10T21:48:48.769Z Info: ltex-ls found in '/Users/deividvale/.vscode/extensions/valentjn.vscode-ltex-13.1.0/lib/ltex-ls-15.2.0'.
2022-06-10T21:48:48.769Z Info: 
2022-06-10T21:48:48.769Z Info: Using ltex-ls from '/Users/deividvale/.vscode/extensions/valentjn.vscode-ltex-13.1.0/lib/ltex-ls-15.2.0'.
2022-06-10T21:48:48.769Z Info: Using Java from '/opt/homebrew/opt/openjdk' (set in ltex.java.path).
2022-06-10T21:48:48.771Z Info: Testing ltex-ls...
2022-06-10T21:48:48.772Z Info:   Command: "/Users/deividvale/.vscode/extensions/valentjn.vscode-ltex-13.1.0/lib/ltex-ls-15.2.0/bin/ltex-ls"
2022-06-10T21:48:48.772Z Info:   Arguments: ["--version"]
2022-06-10T21:48:48.772Z Info:   env['JAVA_HOME']: "/opt/homebrew/opt/openjdk"
2022-06-10T21:48:48.772Z Info:   env['JAVA_OPTS']: "-Xms512m -Xmx1024m"
2022-06-10T21:48:49.223Z Info: Test successful!
2022-06-10T21:48:49.223Z Info: 
2022-06-10T21:48:49.227Z Info: Starting ltex-ls...
2022-06-10T21:48:49.227Z Info:   Command: "/Users/deividvale/.vscode/extensions/valentjn.vscode-ltex-13.1.0/lib/ltex-ls-15.2.0/bin/ltex-ls"
2022-06-10T21:48:49.227Z Info:   Arguments: []
2022-06-10T21:48:49.227Z Info:   env['JAVA_HOME']: "/opt/homebrew/opt/openjdk"
2022-06-10T21:48:49.227Z Info:   env['JAVA_OPTS']: "-Xms512m -Xmx1024m"
2022-06-10T21:48:49.227Z Info:
```

**Comment by CodingTil** [comment]
This approach is not working for me:

```bash
2023-09-19T12:01:54.528Z Info: Setting LTeX UI language to 'en-gb'.
2023-09-19T12:01:54.528Z Info: Loading i18n messages...
2023-09-19T12:01:54.528Z Info: Loading default i18n messages...
2023-09-19T12:01:54.529Z Info: 
2023-09-19T12:01:54.529Z Info: ltex.ltex-ls.path not set.
2023-09-19T12:01:54.529Z Info: Searching for ltex-ls in '/Users/tilmohr/.vscode/extensions/valentjn.vscode-ltex-13.1.0/lib'...
2023-09-19T12:01:54.530Z Info: ltex-ls found in '/Users/tilmohr/.vscode/extensions/valentjn.vscode-ltex-13.1.0/lib/ltex-ls-15.2.0'.
2023-09-19T12:01:54.530Z Info: 
2023-09-19T12:01:54.530Z Info: Using ltex-ls from '/Users/tilmohr/.vscode/extensions/valentjn.vscode-ltex-13.1.0/lib/ltex-ls-15.2.0'.
2023-09-19T12:01:54.530Z Info: Using Java from '/usr' (set in ltex.java.path).
2023-09-19T12:01:54.530Z Info: Testing ltex-ls...
2023-09-19T12:01:54.530Z Info:   Command: "/Users/tilmohr/.vscode/extensions/valentjn.vscode-ltex-13.1.0/lib/ltex-ls-15.2.0/bin/ltex-ls"
2023-09-19T12:01:54.530Z Info:   Arguments: ["--version"]
2023-09-19T12:01:54.530Z Info:   env['JAVA_HOME']: "/usr"
2023-09-19T12:01:54.530Z Info:   env['JAVA_OPTS']: "-Xms64m -Xmx512m"
2023-09-19T12:02:09.532Z Error: Test failed.
2023-09-19T12:02:09.532Z Error: Error details:
2023-09-19T12:02:09.534Z Error: Error: spawnSync /Users/tilmohr/.vscode/extensions/valentjn.vscode-ltex-13.1.0/lib/ltex-ls-15.2.0/bin/ltex-ls ETIMEDOUT
2023-09-19T12:02:09.534Z Error: 	at Object.spawnSync (node:internal/child_process:1110:20)
2023-09-19T12:02:09.534Z Error: 	at Object.spawnSync (node:child_process:931:24)
2023-09-19T12:02:09.534Z Error: 	at DependencyManager.<anonymous> (/Users/tilmohr/.vscode/extensions/valentjn.vscode-ltex-13.1.0/dist/extension.js:13528:45)
2023-09-19T12:02:09.534Z Error: 	at Generator.next (<anonymous>)
2023-09-19T12:02:09.534Z Error: 	at fulfilled (/Users/tilmohr/.vscode/extensions/valentjn.vscode-ltex-13.1.0/dist/extension.js:13159:58)
2023-09-19T12:02:09.534Z Info: ltex-ls terminated due to signal 'SIGTERM'.
2023-09-19T12:02:09.534Z Info: stdout of ltex-ls:
2023-09-19T12:02:09.534Z Info: 
2023-09-19T12:02:09.534Z Info: stderr of ltex-ls:
2023-09-19T12:02:09.534Z Info: 
2023-09-19T12:02:09.534Z Info: You might want to try offline installation, see https://valentjn.github.io/vscode-ltex/docs/installation-and-usage.html#offline-installation.
```

I've also installed java via homebrew and set the `ltex.java.path`, but I get an error 😢

**Comment by CodingTil** [comment]
It works using [Azul Zulu Java 11](https://www.azul.com/downloads/?version=java-11-lts&os=macos&architecture=arm-64-bit&package=jdk#zulu), setting the `ltex.java.path` to `/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home` (which is the installation-location in my case).

Can be installed [here](https://www.azul.com/downloads/?version=java-11-lts&os=macos&architecture=arm-64-bit&package=jdk#zulu) or using homebrew:
```zsh
brew tap homebrew/cask-versions # if not done already
brew install --cask zulu11
```
Java 11 seems to be important though!

**Comment by CodingTil** [comment]
I believe this issue can be resolved in the `ltex-ls`project here: https://github.com/valentjn/ltex-ls/blob/develop/tools/createBinaryArchives.py#L89
