### ISSUE TITLE
Ltex cannot work in remote-ssh environment

### ISSUE THREAD

**Issue by sunyongke** [valentjn/vscode-ltex#711]
remote environment: 

- Ubuntu Kinetic Kudu (development branch) \n \l
-  vscode-ltex-13.1.0

client environment:
- windows+ vscode 1.71.0 + remote-ssh
- Version: 1.71.0 (system setup)
Commit: 784b0177c56c607789f9638da7b6bf3230d47a8c
Date: 2022-09-01T07:36:10.600Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22000
Sandboxed: No

**Describe the bug**
The vscode-LTeX is working on my windows and mac OSX laptop, and everything is working, I can check section, check document, and so on. But cannot work correctly in remote-SSh from windows ssh to ubuntu.   the LTEX language Server outputs follow error information when this extension is activated soon.

I have tested the ltex-cli in the console, and the output is correct,  but the  LTeX language server always crashed when using Ltex in the remote-ssh environment.   

I tried to build the source and find out the issues but failed. 
I  fully expect to get help,  any tip is expected, Please give me some light.

**LTeX Language Server output**

<details>

```
[Info  - 3:33:26 PM] Starting ltex-ls...
Sep 14, 2022 3:33:31 PM org.bsplines.ltexls.server.LtexLanguageServer initialize
INFO: ltex-ls 15.2.1-alpha.1.nightly.2022-09-12 - initializing...
Sep 14, 2022 3:33:31 PM org.bsplines.ltexls.tools.I18n setLocale
INFO: Setting locale to 'en'
Sep 14, 2022 3:33:37 PM org.bsplines.ltexls.settings.SettingsManager$Companion logDifferentSettings
FINE: Reinitializing LanguageTool due to different settings for language 'en-US': setting 'additionalRules.languageModel', old '', new 'en'; setting 'languageToolHttpServerUri', old '', new 'http://218.194.100.28:8081/'; setting 'additionalRules.motherTongue', old '', new 'en-US'
Sep 14, 2022 3:33:37 PM org.bsplines.ltexls.server.DocumentChecker logTextToBeChecked
FINE: Checking the following text in language 'en-US' via LanguageTool: "\n\n\n\n\n\n/home/syk/Documents/home/syk/Documents/home/syk/Documents\n\nB-.05em i-.025em b-.08em T-.1667em."... (truncated to 100 characters)
Sep 14, 2022 3:33:39 PM org.bsplines.ltexls.server.DocumentChecker checkAnnotatedTextFragment
FINE: Obtained 172 rule matches
[Info  - 3:34:01 PM] Connection to server got closed. Server will restart.
Sep 14, 2022 3:34:03 PM org.bsplines.ltexls.server.LtexLanguageServer initialize
INFO: ltex-ls 15.2.1-alpha.1.nightly.2022-09-12 - initializing...
Sep 14, 2022 3:34:03 PM org.bsplines.ltexls.tools.I18n setLocale
INFO: Setting locale to 'en'
Sep 14, 2022 3:34:03 PM org.bsplines.ltexls.server.LtexTextDocumentService didOpen$lambda-1
WARNING: The following exception occurred:
java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Unhandled method ltex/workspaceSpecificConfiguration
	at java.base/java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.get(Unknown Source)
	at org.bsplines.ltexls.server.LtexTextDocumentItem.check(LtexTextDocumentItem.kt:395)
	at org.bsplines.ltexls.server.LtexTextDocumentItem.checkAndGetDiagnostics(LtexTextDocumentItem.kt:295)
	at org.bsplines.ltexls.server.LtexTextDocumentItem.checkAndPublishDiagnostics(LtexTextDocumentItem.kt:272)
	at org.bsplines.ltexls.server.LtexTextDocumentItem.checkAndPublishDiagnosticsWithoutCache(LtexTextDocumentItem.kt:267)
	at org.bsplines.ltexls.server.LtexTextDocumentItem.checkAndPublishDiagnosticsWithoutCache$default(LtexTextDocumentItem.kt:266)
	at org.bsplines.ltexls.server.LtexTextDocumentService.didOpen$lambda-1(LtexTextDocumentService.kt:155)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Unhandled method ltex/workspaceSpecificConfiguration
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:209)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	... 6 more

[Info  - 3:35:01 PM] Connection to server got closed. Server will restart.
Sep 14, 2022 3:35:03 PM org.bsplines.ltexls.server.LtexLanguageServer initialize
INFO: ltex-ls 15.2.1-alpha.1.nightly.2022-09-12 - initializing...
Sep 14, 2022 3:35:03 PM org.bsplines.ltexls.tools.I18n setLocale
INFO: Setting locale to 'en'
Sep 14, 2022 3:35:05 PM org.bsplines.ltexls.server.LtexTextDocumentService didOpen$lambda-1
WARNING: The following exception occurred:
java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Unhandled method ltex/workspaceSpecificConfiguration
	at java.base/java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.get(Unknown Source)
	at org.bsplines.ltexls.server.LtexTextDocumentItem.check(LtexTextDocumentItem.kt:395)
	at org.bsplines.ltexls.server.LtexTextDocumentItem.checkAndGetDiagnostics(LtexTextDocumentItem.kt:295)
	at org.bsplines.ltexls.server.LtexTextDocumentItem.checkAndPublishDiagnostics(LtexTextDocumentItem.kt:272)
	at org.bsplines.ltexls.server.LtexTextDocumentItem.checkAndPublishDiagnosticsWithoutCache(LtexTextDocumentItem.kt:267)
	at org.bsplines.ltexls.server.LtexTextDocumentItem.checkAndPublishDiagnosticsWithoutCache$default(LtexTextDocumentItem.kt:266)
	at org.bsplines.ltexls.server.LtexTextDocumentService.didOpen$lambda-1(LtexTextDocumentService.kt:155)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Unhandled method ltex/workspaceSpecificConfiguration
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:209)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	... 6 more


```

</details>

**Comment by sunyongke** [comment]
I downgrade the Ubuntu server from 22 to 18, and this error has gone. The proper reason is some conflicts with software in newer distributions.

**Comment by sunyongke** [comment]
I downgrade the Ubuntu server from 22 to 18, and this error has gone. The proper reason is some conflicts with software in newer distributions.

**Comment by sunyongke** [comment]
I downgrade the Ubuntu server from 22 to 18, and this error has gone. The proper reason is some conflicts with software in newer distributions.

**Comment by sunyongke** [comment]
I downgrade the Ubuntu server from 22 to 18, and this error has gone. The proper reason is some conflicts with software in newer distributions.
