### ISSUE TITLE
LTEX fails in French because of $\&$

### ISSUE THREAD

**Issue by Leopounet** [valentjn/vscode-ltex#889]
**Describe the bug**
For some reason, I think that `$\&$` _(it actually also makes GitHub fail if it is not in a code block...)_ interferes with LTEX, making it fail. I tested it in French, but it probably happens in any language.

**Steps to reproduce**

1. Create a .tex file.
2. Paste the following text :
```
Tout les nombres
$10$ $0$ $1$
$10^0 = 1$ $10^1 = 10$ $10^2 = 100$
$354$ $<<$ $>>$ 
$|$ $\&$
```

**Expected behavior**
In French, "Tout les nombres" is a mistake, which is correcty detected if the bug does not happen, it should be "Tous les nombres". It is not detected with the given code **but** it is if any dollar sign is deleted, or if a space is added after the ampersand.

**Sample document**
If the bug occurs for a specific document (e.g. LaTeX), please paste it here. If your document is very long or confidential, please create and attach a smaller example for which the bug still occurs so that we can reproduce it.

<details>

```
Tout les nombres
$10$ $0$ $1$
$10^0 = 1$ $10^1 = 10$ $10^2 = 100$
$354$ $<<$ $>>$ 
$|$ $\&$
```

</details>

**LTeX configuration**
I use the default configuration (except that I am using the french language).

**"LTeX Language Server" log file**

<details>

```
Sep 06, 2024 1:26:20 AM org.bsplines.ltexls.server.DocumentChecker logTextToBeChecked
FINE: Checking the following text in language 'fr' via LanguageTool: "Tout les nombres Jimmy-0 Jimmy-1 Jimmy-2 Jimmy-3 Jimmy-4 Jimmy-5 Jimmy-6 Jimmy-7 Jimmy-8 Jimmy-9 &Ji"... (truncated to 100 characters)
Sep 06, 2024 1:26:20 AM org.bsplines.ltexls.server.DocumentChecker checkAnnotatedTextFragment
SEVERE: LanguageTool failed. The following exception occurred:
java.lang.RuntimeException: java.lang.RuntimeException: Could not check sentence (language: French): <sentcontent>Tout les nombres Jimmy-0 Jimmy-1 Jimmy-2 Jimmy-3 Jimmy-4 Jimmy-5 Jimmy-6 Jimmy-7 Jimmy-8 Jimmy-9 &Jimmy-10</sentcontent>
	at org.languagetool.JLanguageTool.performCheck(JLanguageTool.java:1230)
	at org.languagetool.JLanguageTool.checkInternal(JLanguageTool.java:970)
	at org.languagetool.JLanguageTool.check(JLanguageTool.java:900)
	at org.languagetool.JLanguageTool.check(JLanguageTool.java:882)
	at org.languagetool.JLanguageTool.check(JLanguageTool.java:869)
	at org.bsplines.ltexls.languagetool.LanguageToolJavaInterface.checkInternal(LanguageToolJavaInterface.kt:112)
	at org.bsplines.ltexls.languagetool.LanguageToolInterface.check(LanguageToolInterface.kt:22)
	at org.bsplines.ltexls.server.DocumentChecker.checkAnnotatedTextFragment(DocumentChecker.kt:138)
	at org.bsplines.ltexls.server.DocumentChecker.checkAnnotatedTextFragments(DocumentChecker.kt:91)
	at org.bsplines.ltexls.server.DocumentChecker.check(DocumentChecker.kt:279)
	at org.bsplines.ltexls.server.LtexTextDocumentItem.check(LtexTextDocumentItem.kt:413)
	at org.bsplines.ltexls.server.LtexTextDocumentItem.checkAndGetDiagnostics(LtexTextDocumentItem.kt:295)
	at org.bsplines.ltexls.server.LtexTextDocumentItem.checkAndPublishDiagnostics(LtexTextDocumentItem.kt:272)
	at org.bsplines.ltexls.server.LtexTextDocumentItem.checkAndPublishDiagnosticsWithoutCache(LtexTextDocumentItem.kt:267)
	at org.bsplines.ltexls.server.LtexTextDocumentItem.checkAndPublishDiagnosticsWithoutCache$default(LtexTextDocumentItem.kt:266)
	at org.bsplines.ltexls.server.LtexTextDocumentService.didChange$lambda-3(LtexTextDocumentService.kt:227)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: Could not check sentence (language: French): <sentcontent>Tout les nombres Jimmy-0 Jimmy-1 Jimmy-2 Jimmy-3 Jimmy-4 Jimmy-5 Jimmy-6 Jimmy-7 Jimmy-8 Jimmy-9 &Jimmy-10</sentcontent>
	at org.languagetool.JLanguageTool$TextCheckCallable.getOtherRuleMatches(JLanguageTool.java:1883)
	at org.languagetool.JLanguageTool$TextCheckCallable.call(JLanguageTool.java:1765)
	at org.languagetool.JLanguageTool$TextCheckCallable.call(JLanguageTool.java:1736)
	at org.languagetool.JLanguageTool.performCheck(JLanguageTool.java:1226)
	... 21 more
Caused by: java.lang.RuntimeException: fromPos (88) must be less than toPos (88) for match: <sentcontent>FR_SPELLING_RULE:97-103:Faute de frappe possible trouvée.</sentcontent>
	at org.languagetool.rules.RuleMatch.setOffsetPosition(RuleMatch.java:326)
	at org.languagetool.JLanguageTool.adjustRuleMatchPos(JLanguageTool.java:1345)
	at org.languagetool.JLanguageTool$TextCheckCallable.getOtherRuleMatches(JLanguageTool.java:1856)
	... 24 more
```

</details>

**"LTeX Language Client" log file**

<details>

```
[Trace - 01:30:25] Sending request 'textDocument/codeAction - (314)'.
Params: {
    "textDocument": {
        "uri": "file:///home/leop/Downloads/main.tex"
    },
    "range": {
        "start": {
            "line": 4,
            "character": 8
        },
        "end": {
            "line": 4,
            "character": 8
        }
    },
    "context": {
        "diagnostics": []
    }
}


[Trace - 01:30:25] Received response 'textDocument/codeAction - (314)' in 2ms.
Result: []


[Trace - 01:30:26] Sending notification 'textDocument/didSave'.
Params: {
    "textDocument": {
        "uri": "file:///home/leop/Downloads/main.tex"
    }
}


[Trace - 01:30:31] Sending notification 'textDocument/didSave'.
Params: {
    "textDocument": {
        "uri": "file:///home/leop/Downloads/main.tex"
    }
}
```

</details>

**Version information**
List here the version information of the relevant software.

- Operating system: Ubuntu 22.04 ; 6.8.0-40-generic
- VS Code: 1.92.2
- vscode-ltex: 13.1.0
- Java: 21.0.1

**Comment by EliottPaq** [comment]
hey i've got the same Issue too didn't knew it was due to the french settings, but after I check out in the settings, using "en-US" don't show this error, it's really weird
