### ISSUE TITLE
Request textDocument/codeAction failed.

### ISSUE THREAD

**Issue by walliski** [valentjn/vscode-ltex#9]
Hey

Getting this error when opening my ~1800 line latex document. It appears multiple times in the "LanguageTool client" output.

Plugin version 4.6.10, language en-us 4.6.9

Overall difficult to know if the plugin is doing something at all, except for when it starts to spike to 100% CPU usage 🙈 

Looking forward to see what this project ends up as though, helpful to get some more language checking into VSCode!

```
[Error - 13.49.42] Request textDocument/codeAction failed.
  Message: Internal error.
  Code: -32603 
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	... 11 more
Caused by: java.lang.RuntimeException: latex.AnnotatedTextBuilder failed.
	at LanguageToolLanguageServer.validateDocument(LanguageToolLanguageServer.java:463)
	at LanguageToolLanguageServer.access$000(LanguageToolLanguageServer.java:26)
	at LanguageToolLanguageServer$1.codeAction(LanguageToolLanguageServer.java:262)
	... 15 more
Caused by: java.util.concurrent.TimeoutException
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at LanguageToolLanguageServer.validateDocument(LanguageToolLanguageServer.java:461)
	... 17 more
```

**Comment by valentjn** [comment]
Thanks for reporting. Does the extension work for small documents with little content? If yes, could you upload your long LaTeX file? If it's confidential, could you try to create a smaller example for which it doesn't work?

**Comment by walliski** [comment]
It did successfully parse my README.md file that I have in the same project.

Unfortunately I cannot upload the LaTeX file. I'll see if I could try out with smaller versions of the same file/content type.

**Comment by valentjn** [comment]
LT<sub>E</sub>X version 4.6.11 just got released; relevant changes for this issue:
1. Fixes for files with non-Linux line endings that led to an infinite loop.
2. Prevention of infinite loops (caused by other unknown bugs) by naively skipping problematic characters while parsing.
3. More helpful debug info (by logging a warning) in case it would get stuck in an infinite loop again.

@walliski This should at least prevent the 100% CPU usage for you due to point 2. In case you have Windows/Mac line endings (i.e. point 1), this might completely fix your issue. Otherwise, there should be a warning in the log file (`vscode-ltex.log` in the workspace storage folder). In this case, please post the new debug info (point 3) given there.

**Comment by walliski** [comment]
@valentjn 

The 4.6.11 update seemed to fix the issues for me! Now it gave me 1000 issues to fix in less than a minute 👍  😬 

After that CPU usage went back to normal. I did not see the error I posted originally, so I will close this issue.
